project:
  type: website
  output-dir: docs
  preview: 
    port: 5556
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: auto
  warning: false

website:
  title: "Lunbo Zhang"
  site-url: https://zlbzlbzzz.github.io/zhanglunbo.github.io
  repo-url: https://github.com/zlbzlbzzz/zhanglunbo.github.io
 #google-analytics: "G-EX523L4LWJ"
  open-graph: true
  navbar:
    right:
      - text: About
        file: about/index.qmd
      - text: Research
        file: research/index.qmd
      - text: Resources
        file: software/index.qmd
      - text: Blog
        file: blog/index.qmd
      - text: CV
        href: /cv/cv.pdf
  page-footer:
    left: |
      <span class="faux-block">© 2025 Lunbo Zhang</span>
     # <span class="faux-block">{{< fa brands orcid >}} <strong>ORCID</strong> [{{< var orcid >}}](https://orcid.org/{{< var orcid >}})</span>
    right: |
      Contact&nbsp;Me:
      <a href="mailto:zhanglunbo@hnu.edu.cn">zhanglunbo@hnu.edu.cn</a>
      
format:
  html:
    theme: 
      - static/html/custom.scss
    include-in-header:
      - text: |
          <!-- 引入 Font Awesome 6 样式表 -->
          <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
            integrity="sha512-pc6O+3fBtVtL2hW0D1TYJWtkK5JVl4tgDpVS0SgXDZJQYozxjEv0zZKULeKPohInAwW0PhvQg5LRR8vxP2R3MQ=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer" />

bibliography: references.bib




